-- ============================================================
-- V3: Import middleware inventory data
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Insert business systems

INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('营业厅前台', '营业厅前台', 'BUSINESS', 'admin', 'C11', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('JCRM', 'jcrm', 'BUSINESS', 'admin', 'C11', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('微服务', '微服务', 'BUSINESS', 'admin', 'C11', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('能开', '能开', 'BUSINESS', 'admin', 'C51', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('一级BOSS', '一级boss', 'BUSINESS', 'admin', 'N51', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('大音', '大音', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('客服工作流', '客服工作流', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('知识库', '知识库', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('5G消息营业厅', '5g消息营业厅', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('政企H5', '政企h5', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('SIGNINLOCATION', 'signInlocation', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('TRACKEROPS', 'trackerops', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);
INSERT INTO t_business_system (system_code, system_name, domain, responsible_person, description, enabled, created_at, updated_at) VALUES ('后台进程', '后台进程', 'BUSINESS', 'admin', '', TRUE, NOW(), NOW()) ON DUPLICATE KEY UPDATE system_name = VALUES(system_name), domain = VALUES(domain);

-- Insert inventory records

INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0001', 1, 'zookeeper', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0002', 1, 'redis', '22.300.0.B424.1020 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0003', 1, 'vsearch', 'V600R002C13SPC001', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0004', 1, 'nslb', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0005', 1, 'jdk', 'jdk1.8.0_222', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0006', 1, 'zookeeper', 'v600r002c18spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0007', 1, 'redis', '22.300.0.03271 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0008', 1, 'vsearch', 'V600R002C18', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0009', 1, 'nslb', 'v600r002c18', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0010', 1, 'jdk', 'jdk1.8.0_402', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0011', 1, 'zookeeper', '3.4.6 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0012', 1, 'redis', '5.0.3哨兵模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0013', 1, 'vsearch', 'V600R001C10', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0014', 1, 'ingress', 'v0.34.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0015', 1, 'jdk', 'jdk.1.8.0_191', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0016', 1, 'nginx', '1.23.4静态资源服务器', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0017', 1, 'prometheus', 'nodeexport1.3.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0018', 1, 'ingress', '0.30.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '营业厅前台' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0019', 1, 'zookeeper', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0020', 1, 'redis', '22.300.0.B424.1020 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0021', 1, 'nslb', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0022', 1, 'jdk', 'jdk1.8.0_222', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0023', 1, 'zookeeper', 'v600r002c18spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0024', 1, 'redis', '22.300.0.03271 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0025', 1, 'nslb', 'v600r002c18', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0026', 1, 'jdk', 'jdk1.8.0_402', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0027', 1, 'zookeeper', '3.4.6 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0028', 1, 'redis', '5.0.3哨兵模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0029', 1, 'ingress', 'v0.34.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0030', 1, 'prometheus', 'nodeexport1.3.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0031', 1, 'ingress', '0.30.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0032', 1, 'jdk', 'jdk1.8.0_212', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'JCRM' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0033', 1, 'zookeeper', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0034', 1, 'redis', '22.300.0.B424.1020 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0035', 1, 'vsearch', 'V600R002C13SPC001', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0036', 1, 'nslb', 'v600r002c13spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0037', 1, 'jdk', 'jdk1.8.0_222', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0038', 1, 'zookeeper', 'v600r002c18spc002', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0039', 1, 'redis', '22.300.0.03271 哨兵加固版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0040', 1, 'vsearch', 'V600R002C18', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0041', 1, 'nslb', 'v600r002c18', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0042', 1, 'jdk', 'jdk1.8.0_402', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0043', 1, 'zookeeper', '3.4.6 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0044', 1, 'redis', '5.0.3哨兵模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0045', 1, 'vsearch', 'V600R001C10', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0046', 1, 'ingress', 'v0.34.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0047', 1, 'jdk', 'jdk1.8.0_202', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0048', 1, 'prometheus', 'nodeexport1.3.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0049', 1, 'ingress', '0.30.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '微服务' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0050', 1, 'zookeeper', '3.4.2开源版本 ,3.6.3开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0051', 1, 'redis', '3.2.8 cluster模式 ,6.2.7 cluster模式', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0052', 1, 'vsearch', '2.12_2.81', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0053', 1, 'jdk', '1.8.0_171', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0054', 1, 'nginx', 'Openresty1.11.2.2 nginx 1.20.1 nginx 1.22.1 nginx 1.22.4', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0055', 1, 'elk', '6.3.2', 'DATA_STORE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0056', 1, 'prometheus', 'nodeexport1.3.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0057', 1, 'zookeeper', '3.5.5 —磐基部署维护', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0058', 1, 'redis', '6.0.9 cluster模式 - 磐基部署维护', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0059', 1, 'vsearch', '2.13-2.6.1 - 磐基部署维护', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0060', 1, 'nginx', 'Openresty1.11.2.2', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '能开' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0061', 1, 'zookeeper', '3.4.6 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0062', 1, 'redis', '5.0.3 cluster模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0063', 1, 'vsearch', '2.11-2 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0064', 1, 'ingress', 'v0.34.1 v0.34.1_fix', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0065', 1, 'jdk', '1.8.0_191', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0066', 1, 'elk', '6.3.2', 'DATA_STORE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0067', 1, 'prometheus', 'nodeexport1.3.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '一级BOSS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0068', 1, 'redis', '6.0.9 cluster模式 - 磐基部署维护', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '大音' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0069', 1, 'nginx', 'nginx 1.20.2 - 磐基维护部署', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '磐基', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '大音' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0070', 1, 'Apache', '2.4.58', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '客服工作流' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0071', 1, 'zookeeper', '3.6.2 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '知识库' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0072', 1, 'redis', '5.0.6 cluster模式 开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '知识库' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0073', 1, 'nginx', 'nginx: openresty/1.19.3.2', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '知识库' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0074', 1, 'elk', 'elasticsearch 7.10.2 logstash 6.3.2', 'DATA_STORE', 'admin', bs.id, 'PRODUCTION', 1, '现网', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '知识库' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0075', 1, 'redis', '5.0.3哨兵模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '5G消息营业厅' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0076', 1, 'jdk', '1.8.0_171', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '5G消息营业厅' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0077', 1, 'nginx', '1.26.3', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '5G消息营业厅' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0078', 1, 'redis', '6.2.12哨兵模式，开源版本', 'MESSAGE_QUEUE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '政企H5' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0079', 1, 'jdk', '1.8.0_402', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '政企H5' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0080', 1, 'nginx', '1.23.4', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '政企H5' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0081', 1, 'jdk', '1.8.0_191', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'SIGNINLOCATION' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0082', 1, 'nginx', '1.22.1', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'SIGNINLOCATION' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0083', 1, 'zookeeper', '3.6.2 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0084', 1, 'vsearch', '2.12-2.5.1', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0085', 1, 'jdk', '1.8.0_201', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0086', 1, 'nginx', '1.23.4', 'WEB_SERVER', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0087', 1, 'elk', 'elasticsearch 7.3.1 kibana:7.3.1 filebeat:7.3.1&7.13.3', 'DATA_STORE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0088', 1, 'prometheus', 'prometheus:2.34.0 grafana:8.3.6', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0089', 1, 'hadoop_hbase', 'hadoop:2.10.1 hbase:2.2.4', 'DATA_STORE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = 'TRACKEROPS' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0090', 1, 'zookeeper', '3.4.6 开源版本', 'MIDDLEWARE', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '后台进程' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);
INSERT INTO t_inventory_record (record_no, user_id, package_name, version_no, software_type, responsible_person, business_system_id, deploy_environment, server_count, usage_scenario, source_type, status, created_at, updated_at) SELECT 'INV-20260413-0091', 1, 'jdk', '1.8.0_191', 'RUNTIME', 'admin', bs.id, 'PRODUCTION', 1, '', 'IMPORT', 'APPROVED', NOW(), NOW() FROM t_business_system bs WHERE bs.system_code = '后台进程' ON DUPLICATE KEY UPDATE version_no = VALUES(version_no);

SET FOREIGN_KEY_CHECKS = 1;

-- -----------------------------------------------------------------------------
-- Update schema version
-- -----------------------------------------------------------------------------

INSERT INTO t_system_config (config_key, config_value, description, updated_at) VALUES
    ('schema_version', '3', '数据库架构版本', NOW())
ON DUPLICATE KEY UPDATE
    config_value = '3',
    updated_at = NOW();